config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  # 顧客用
  # URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  scope module: :user do
    resources :users, only: [:index, :show, :edit, :update]
    get "search" => "posts#search"
  end

  root to: "user/homes#top"
  get 'about' => 'user/homes#about'


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
      resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  namespace :admin do

  end

  namespace :admin do

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :audio
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_and_tags, dependent: :destroy
  has_many :tags, through: :post_and_tags

  def find_bookmark(user)
    bookmarks.find_by(user_id: user.id)
  end

  def find_bookmark(admin)
    bookmarks.find_by(@user_id)
  end

  def self.search(keyword)
    where("title LIKE ? or body LIKE ?", "%#{keyword}%", "%#{keyword}%" )
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/post_and_tag.rb
class PostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_and_tags, dependent: :destroy
  has_many :posts, through: :post_and_tags

  validates :tag_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  #フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  #フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  #いいね機能
  def favorited_by?(post)
    favorites.exists?(post_id: post.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def get_profile_image(height, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [height, width] ).processed
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page])
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "新しいタグを追加しました。"
    else
      @tags = Tag.page(params[:page])
      flash.now[:alert] = "タグの追加に失敗しました。"
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの更新に成功しました。"
    else
      flash.now[:alert] = "タグの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end

  private
  def tag_params
    params.require(:tag).permit(:tag_type, :tag_ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action do # ActiveStorageのurlメソッドを使用できるようにする
    ActiveStorage::Current.host = request.base_url
  end


  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/post_helper.rb
module Admin::PostHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/tags/_error.html.erb
 <div class="row">
    <div class="col-lg-10 text-center">
    <% if tag.errors.any? %>
      <%= tag.errors.count %>件のエラーが発生しました
      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    </div>
  </div>

app/views/admin/tags/edit.html.erb
<div class="container border border-white contents-area bg-white" >
<div class="row mt-4 md-2">
  <div class="col-md-6 mx-auto">

    <%= render "error", tag: @tag %>

    <h3><strong><%= flash[:alert] %></strong></h3>
    <h3><strong class="border-bottom border-dark">タグ編集</strong></h3>

      <%= form_with model: @tag, url:admin_tag_path,method: :patch do |f| %>
        <table class="table table-borderless mt-3">
          <tbody>
            <tr>
              <td class="align-middle">
                <label for="genre_name">タグ名</label>
              </td>
              <td class="align-middle">
                <%= f.text_field:tag_type %>
              </td>
              <td>
                <%= f.submit "変更を保存",class: "btn btn-success",  method: :patch, "data-confirm" => "このタグを変更した場合、投稿者のタグも同時に変更されます。本当に変更してよろしいですか?"  %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container" >
  <div class="row">
    <div class="col-lg-12 text-center text-white tagname">

      <%= render "error", tag: @tag %>

      <h3><strong><%= flash[:notice] %><%= flash[:alert] %></strong></h3>
      <h3><strong class="border-bottom border-white">タグ一覧・追加/削除</strong></h3>

      <%= form_with model: @tag, url: admin_tags_path,method: :post do |f| %>
        <table class="table table-border contents-area mt-5">
          <tbody>
            <tr>
              <td class="align-middle">タグ名</td>
              <td class="center align-middle">
                <%= f.text_field:tag_type,:size=>"35" %>
              </td>
              <td>
                <%= f.submit "新規登録", class: "btn btn-outline-light mx-auto btn-lg" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>

    <div class="col-lg-12 text-center text-white tags">
      <table class="table table-hover table-inverse">
        <thead>
          <tr class="text-white">
            <th><h3><strong>タグの名前</strong></h3></th>
            <th><h4>タグの変更</h4></th>
            <th><h4>タグの削除</h4></th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
          <tr class="text-white">
            <td><%= tag.tag_type %></td>
            <td><%= link_to "変更する", edit_admin_tag_path(tag.id), class: "btn btn-outline-light mx-auto" %></td>
            <td><%= link_to "削除する", admin_tag_path(tag.id), class: "btn btn-outline-danger mx-auto", 
                                             method: :delete, "data-confirm" => "本当にタグを削除しますか?" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      
      <div class="pagination justify-content-center mt-3">
        <%= paginate @tags %>
      </div>

    </div>
  </div>
</div>