config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  # 顧客用
  # URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  scope module: :user do
    resources :users, only: [:index, :show, :edit, :update]
    get "search" => "posts#search"
  end

  root to: "user/homes#top"
  get 'about' => 'user/homes#about'


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
      resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  namespace :admin do

  end

  namespace :admin do

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :audio
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_and_tags, dependent: :destroy
  has_many :tags, through: :post_and_tags

  def find_bookmark(user)
    bookmarks.find_by(user_id: user.id)
  end

  def find_bookmark(admin)
    bookmarks.find_by(@user_id)
  end

  def self.search(keyword)
    where("title LIKE ? or body LIKE ?", "%#{keyword}%", "%#{keyword}%" )
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/post_controller.rb
class Admin::PostController < ApplicationController
  before_action :authenticate_user!
　before_action :if_not_admin
  before_action :set_post, only: [:index, :show, :edit, :update, :destroy]

  def index
    @post = Post.page(params[:page])
    if params[:new_post]
      @posts = Post.new_post
    elsif params[:old_post]
      @posts = Post.old_post
    else
      @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    end
    if params[:keyword]
      @posts = @posts.search(params[:keyword]).page(params[:page])
    else
      @post = @posts.page(params[:page])
    end
    @keyword = params[:keyword]
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :index
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def set_post
    @post = post.find(params[:id])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.page(params[:page])
    if params[:new_post]
      @posts = Post.new_post
    elsif params[:old_post]
      @posts = Post.old_post
    else
      @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    end
    if params[:keyword]
      @posts = @posts.search(params[:keyword]).page(params[:page])
    else
      @post = @posts.page(params[:page])
    end
    @keyword = params[:keyword]
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post.id)
    else
      render :index
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:user_id, :body, :title, :image, :audio, :facility_name, :tag_ids )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @users = User.all.page(params[:page])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "会員情報を編集しました"
    redirect_to admin_user_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :is_deleted)
  end
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @post = @bookmark.post
    if @bookmark.valid?
      @bookmark.save
      redirect_to post_path(@post), notice: "お気に入りに登録しました。"
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @post = @bookmark.post
    if @bookmark.destroy
      redirect_to post_path(@post), notice: "お気に入り登録を解除しました。"
    end
  end
  
  private
  
  def bookmark_params
    params.permit(:post_id)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    #redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    #redirect_to posts_path
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end

  def guest_sign_in
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController

  before_action :authorize_user, only: [:edit, :update, :destroy]

  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    #@post = Post.includes(:favorites).where(user_id: current_user.id)
    @post = Post.page(params[:page])
    if params[:new_post]
      @posts = Post.new_post
    elsif params[:old_post]
      @posts = Post.old_post
    else
      @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    end
    if params[:keyword]
      @posts = @posts.search(params[:keyword]).page(params[:page])
    else
      @post = @posts.page(params[:page])
    end
    @keyword = params[:keyword]
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @user = User.find(params[:id])
  end

  def edit
   @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :body, :title, :image, :audio, :facility_name, :tag_ids )
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  #フォローをするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  #フォローを外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  #フォローの一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  #フォロワーの一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/views/user/posts/_bookmark.html.erb
<% if current_user != @post.user %>
  <div class="bookmark">
    <% if @post.find_bookmark(current_user).blank? %>
      <%= link_to "お気に入りに登録", post_bookmarks_path(@post), method: :post, class: "btn btn-outline-light mx-auto btn-lg" %>
    <% else %>
      <%= link_to "お気に入りを解除", post_bookmark_path(@post,@post.find_bookmark(current_user)), method: :delete, 
                                                                    class: "btn btn-outline-danger mx-auto btn-lg" %>
      <% end %>
  </div>
<% end %>

app/views/user/posts/_comment.html.erb
<div class="col-lg-12 comment">
  <table class="table table-hover table-inverse">
    <thead>
      <tr class="text-white">
        <th align="center"><h3><strong>コメント</strong></h3></th>
      </tr>
      </tr>
    </thead>
    <tbody>
      <% post.post_comments.each do |post_comment| %>
      <tr class="text-white">
        <td align="center">
        <p><%= image_tag post_comment.user.get_profile_image(50, 50), class: "rounded-circle" %>　　<strong><%= post_comment.user.name %></strong></p>
          
        <h5><%= post_comment.comment %></h5>
          
        <%= post_comment.created_at.strftime('%Y/%m/%d') %>
          
        <% if post_comment.user == current_user %>
          <%= link_to "コメント削除", post_post_comment_path(post_comment.post, post_comment), class: "btn btn-outline-danger", method: :delete %>
        <% end %>
      </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/user/posts/_editpost.html.erb
  <div class="row">
    <div class="col-lg-12 text-center text-white posts edit">
      
    <%= form_for(@post, url: post_path(@post)) do |f| %>
    
      <div class="field">
        <%= f.label :アーティスト写真 %><br>
        <%= f.file_field :image, accept: "image/*", :placeholder =>"#{@post.body}" %>
      </div>
      
      <div class="field mt-2">
        <%= f.label :アーティスト名 %><br>
        <%= f.text_field :title, autofocus: true, :placeholder =>"#{@post.title}" %>
      </div>
  
      <div class="field mt-3">
        <%= f.label :共有する曲 %><br>
        <%= f.file_field :audio, accept: "audio/*", :placeholder =>"#{@post.body}" %>
      </div>
  
      <div class="field mt-2">
        <%= f.label :曲名・おすすめ理由 %><br>
        <%= f.text_area :body, :placeholder =>"#{@post.body}" %>
      </div>
  
      <div class="form-group mt-3"><strong>タグ</strong></div>
      <div class="row d-flex justify-content-start m-2">
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_type) do |tag| %>
          <div class="form-check form-check-inline flex flex-wrap">
            <%= tag.label do %>
              <%= tag.check_box %>
              <%= tag.text %>
            <% end %>
          </div>
        <% end %>
      </div>
      
      <div class="mt-2"><%= f.submit "更新する", class: "btn btn-outline-light mx-auto"%></div>
    <% end %>
  </div>
</div>

app/views/user/posts/_error.html.erb
  <div class="row">
    <div class="col-lg-10 text-center">
    <% if post.errors.any? %>
      <%= post.errors.count %>件のエラーが発生しました
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    </div>
  </div>

app/views/user/posts/_list.html.erb
<% posts.in_groups_of(3, false) do |post_group| %>
  <div class="row ">
      <% post_group.compact.each do |post| %>
        <div class="col-lg-5 text-center text-white toukou">
          <p>
            <%= image_tag post.user.get_profile_image(50, 50), class: "rounded-circle" %>
            <%= post.user.name %>
            <%= post.created_at.strftime('%Y/%m/%d') %>
          </p>

          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_image, size: '200x150' %>
          <% end %>

          <p><%= post.title %></p>
          <p><%= post.body %></p>
          <div id="waveform_<%= post.id %>">
            <!-- the waveform will be rendered here -->
          </div>
          <script>
            const wavesurfer_<%= post.id %> = WaveSurfer.create({
              container: '#waveform_<%= post.id %>',
              waveColor: 'white',
              progressColor: '#EDFFBE',
              url: '<%= post.audio.url %>',
            })
          </script>
          <button onclick="wavesurfer_<%= post.id %>.playPause()">再生・停止</button>

            <span id="favorite_buttons_<%= post.id %>" >
              <%= render "user/favorites/favorite", post: @post %>
            </span>

          <% post.tags.each do |tag| %>
            <%= tag.tag_type %>
          <% end %>
        </div>
      <% end %>
  </div>
<% end %>

app/views/user/posts/_post.html.erb
<%= form_with model: @post do |f| %>
  <div class="field">
    <%= f.label :アーティスト写真 %><br>
    <%= f.file_field :image, accept: "image/*", :placeholder =>"#{@post.body}" %>
  </div>
      
  <div class="field">
    <%= f.label :アーティスト名 %><br>
    <%= f.text_field :title, autofocus: true, :placeholder =>"#{@post.title}" %>
  </div>
      
  <div class="field mt-2">
    <%= f.label :共有する曲 %><br>
    <%= f.file_field :audio, accept: "audio/*", :placeholder =>"#{@post.body}" %>
  </div>
      
  <div class="field mt-2">
    <%= f.label :曲名・おすすめ理由 %><br>
    <%= f.text_area :body, :placeholder =>"#{@post.body}" %>
  </div>
      
  <div class="form-group mt-2"><strong>タグ</strong></div>
  
  <div class="row d-flex justify-content-start m-4">
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_type) do |tag| %>
    <div class="form-check form-check-inline flex flex-wrap">
    <%= tag.label do %>
      <%= tag.check_box %>
      <%= tag.text %>
    <% end %>
    </div>
  <% end %>
  </div>
  
  <div class="row mt-3">
    <div class="col-lg-12 text-center">
      <%= f.submit '共有する', class: "btn btn-outline-light mx-auto" %>
    </div>
  </div>
<% end %>

app/views/user/posts/_search.html.erb
<div class="d-flex justify-content-end text-white sideber">
  <%= form_with url: posts_path, method: :get, local: true, class: 'boards__searchForm' do |f|%>
    <div class="input-group">
      <%= f.text_field :keyword, value: @keyword, class: "form-control search-control", placeholder: "キーワードを入力" %>
        <span class="input-group-btn input-group-append">
        <%= button_tag type: "submit", class: "btn btn-outline-light search-btn" do %>
          <i class="fas fa-search"></i> 検索</submit>
        <% end %>
      </span>
    </div>
    <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_type, params[:tag_id]),{prompt: "タグで絞り込み検索",onchange: "submit(this.form);"} %>
  <% end %>
</div>

app/views/user/posts/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-lg-12 text-center text-white">
      <h1><strong>投稿の編集</strong></h1>
    </div>
  </div>
  
  <%= render "error", post: @post %>
  <%= render "editpost", post: @post %>
  
</div>

app/views/user/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center text-white midashi">
      <h1><strong>投稿一覧</strong></h1>
    </div>
    <div class="col-lg-4 ">
      <%= render "search", post: @post %>
    </div>
    <div class="col-lg-8">
      <%= render 'list', posts: @posts %>
    </div>
  </div>
</div>

app/views/user/posts/new.html.erb
<div class="container">
  <div class="row d-flex align-items-center justify-content-center">
    
    <div class="col-lg-12 text-center text-white midashi">
      <h1><strong>共有フォーム</strong></h1>
    </div> 
    
    <%= render "error", post: @post %>
    
    <div class="col-lg-12 text-center text-white kyouyuu">
      <%= render "post", post: @post %>
    </div>
  </div>
</div>

app/views/user/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center text-white midashi">
      <h1><strong>投稿詳細</strong></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-7 text-center text-white post-show">

        <div class="row">
          <div class="col-6 profile-photo">
            <%= image_tag @post.user.get_profile_image(100,100), class: "rounded-circle" %>
            <strong><%= @post.user.name %></strong>
          </div>

          <div class="col-5 follow">
            <% if current_user.following?(@user) %>
              <%= link_to "フォロー外す", post_relationships_path(@user.id), class: "btn btn-outline-light", method: :delete %>
            <% else %>
              <%= link_to "フォローする", post_relationships_path(@user.id), class: "btn btn-outline-light", method: :post %>
            <% end %>
          </div>
        </div>

        </p>
        <p><%= image_tag @post.get_image, :size =>'300x200' %></p>
        <p><%= @post.title %></p>

        <div class="row">
          <div class="col-lg-12 text-center">
            <div id="waveform_<%= @post.id %>">
              <!-- the waveform will be rendered here -->
            </div>
          </div>
        </div>
        <script>
          const wavesurfer_<%= @post.id %> = WaveSurfer.create({
            container: '#waveform_<%= @post.id %>',
            waveColor: 'white',
            progressColor: '#EDFFBE',
            url: '<%= rails_blob_path(@post.audio) %>',
          })
        </script>

        <button onclick="wavesurfer_<%= @post.id %>.playPause()">再生・停止</button>
        <p>曲名と概要：<%= @post.body %></p>

        <% @post.tags.each do |tag| %>
          <table class="table table-bordered table-hover bg-white mb-5">
            <tbody>
              <tr>
                <th style="width: 30%">タグ</th>
                <td style="width: 70%"><%= tag.tag_type %></td>
              </tr>
            </tbody>
          </table>
        <% end %>

        <%= form_with model: [@post, @post_comment] do |f| %>
        <div class="row">
          <div class="col-7 comment">
            <%= f.text_area :comment, size: "30x5", placeholder: "コメントをする"  %>
          </div>
          <div class="col-5 comment-btn">
            <%= f.submit "送信する", class: "btn btn-outline-light" %>
            コメント数：<%= @post.post_comments.count %>
          </div>
        </div>
        <% end %>

        <% if @post.user == current_user %>
          <%= link_to "投稿の編集", edit_post_path(@post), class: "btn btn-outline-light" %>
          <%= link_to "投稿の削除", post_path(@post), class: "btn btn-outline-light", method: :delete %>
        <% end %>

        <%= render "bookmark", post: @post %>

        投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %>
      </div>

      <div class="col-4 text-center text-white comment-show">
        <%= render "comment", post: @post %>
      </div>
    </div>
  </div>
</div>